### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AndryHTC** [smjburton/vbase#1]
I really need some documentation, especially for HTML document/parser. Can you explain the logic of the main functions?

**Comment by smjburton** [comment]
Sure, currently on vacation, but I’ll be back next week. Can you send me an e-mail on Monday and let me know what you’re trying to do?

Scott

________________________________

**Comment by AndryHTC** [comment]
Hi Scott!
I’m trying to do a jQuery similar framework in classic ASP/VBS (server side, so is not live, only for managing html). I don’t know really how to use this, but seems to be a lot powerfull parsing html.

For example, I need to do something like this (the example is not related to your library, it is only for explaining):

set object = html_dom
object.fromHtml(“<div class=’parent’><span></span><span class=’child-wanted’></span></div>”)
object.find(“span.child-wanted”).addClass(“new-class”).attr(“title”,”Hello”)
object.find(“div > span:first-child”).remove()
response.write  object

<div class=’parent’>
                <span class=’child-wanted new-class’ title=’Hello’></span>
</div>”

So I will create an object wrapping your object. But I need to understand how to navigate dom, change classes, attributes, remove childs ecc… to create something like this.

Thank you for your time!
Andrea Giacon

Da: Scott Burton<mailto:notifications@github.com>
Inviato: giovedì 12 aprile 2018 21:29
A: smjburton/vbase<mailto:vbase@noreply.github.com>
Cc: AndryHTC<mailto:andryhtc@live.it>; Author<mailto:author@noreply.github.com>
Oggetto: Re: [smjburton/vbase] Documentation (#1)

Sure, currently on vacation, but I’ll be back next week. Can you send me an e-mail on Monday and let me know what you’re trying to do?

Scott

________________________________

**Comment by AndryHTC** [comment]
Please, can you send me a short reply? At least if is possibile or not.

**Comment by smjburton** [comment]
It would be possible, but you’d have to modify the library. Currently, the library only allows you to retrieve the object and/or data, not add, change, or remove objects/data in the DOM. You’d have to add code to be able to modify the DOM object itself.

You can load an HTML string into the parser using the sub FromString(). For example:

Dim objHtmlParser as v_HTML_Parser
Set objHtmlParser = New v_HTML_Parser

objHtmlParser.FromString(“<div class=’parent’><span></span><span class=’child-wanted’></span></div>”)

From there, the object uses the chaining design pattern to return an instance of itself for every function that helps narrow down your selection. Then you could do something like:

MsgBox objHtmlParser.Selector(“span.child-wanted”).HTML

To get the HTML of the object, but you’d need to add functions to change, remove, or add to the actual object.

Does this help?

Scott

________________________________

**Comment by AndryHTC** [comment]
Thank you for the advise. Have you got some ideas how to make those functions? I think for someone that has not created the library, could be very tricky

Andrea Giacon

________________________________
Da: Scott Burton <notifications@github.com>
Inviato: Sunday, April 22, 2018 4:01:36 PM
A: smjburton/vbase
Cc: AndryHTC; Author
Oggetto: Re: [smjburton/vbase] Documentation (#1)

It would be possible, but you’d have to modify the library. Currently, the library only allows you to retrieve the object and/or data, not add, change, or remove objects/data in the DOM. You’d have to add code to be able to modify the DOM object itself.

You can load an HTML string into the parser using the sub FromString(). For example:

Dim objHtmlParser as v_HTML_Parser
Set objHtmlParser = New v_HTML_Parser

objHtmlParser.FromString(“<div class=’parent’><span></span><span class=’child-wanted’></span></div>”)

From there, the object uses the chaining design pattern to return an instance of itself for every function that helps narrow down your selection. Then you could do something like:

MsgBox objHtmlParser.Selector(“span.child-wanted”).HTML

To get the HTML of the object, but you’d need to add functions to change, remove, or add to the actual object.

Does this help?

Scott

________________________________

**Comment by smjburton** [comment]
Hi Andrea,

You may want to look at my v_HTML_Document library instead (https://github.com/smjburton/v_HTML_Document/blob/master/v_HTML_Document.vbs). This library will allow you to add and remove HTML elements to and from the DOM.

You might be able to do something like this:

              Include "v_HTML_Document"

              Dim objHtmlDoc, _
                             objChildWanted

              Set objHtmlDoc = New v_HTML_Document

              objHtmlDoc.WriteLn "<html><head></head><body><div class='parent'><span>" & _
                                                          "</span><span class='child-wanted'></span></div>" & _
                                                          "</body></html>"

              Set objChildWanted = objHtmlDoc.QuerySelector("span.child-wanted")

              With objChildWanted
                             .setAttribute "class", "new-class"
                             .setAttribute "title", "Hello"
              End With

              WScript.Echo objChildWanted.outerHTML

              objChildWanted.parentNode.removeChild(objChildWanted)

              WScript.Echo objHtmlDoc.HTML

I quickly tested this code and it seems to work for what you want to do. Let me know if you need anything else.

Scott
